version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      # POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - .env

    ports:
      - "5432:5432"
    volumes:
      - ./table/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default
      # - internnal: true

  app:
    build: .
    restart: always
    depends_on:
      - db
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
    - "8080:8080"
    networks:
      - default

# networks:
#   myNetwork:
#     driver: custom-driver-1